### 1. Numpy Installation

In [ ]:
# installing aspecific version
pip install numpy==1.24

In [25]:
# checking version
pip show numpy

Name: numpy
Version: 1.22.4
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: c:\users\pak\anaconda3\lib\site-packages
Requires: 
Required-by: xgboost, transformers, torchvision, tifffile, tensorflow-intel, tensorflow-hub, tensorboard, tables, statsmodels, stanza, shapely, sentence-transformers, seaborn, scipy, scikit-learn, scikit-image, PyWavelets, pyerfa, pyarrow, patsy, pandas, opt-einsum, opencv-python, numexpr, numba, ml-dtypes, mkl-random, mkl-fft, matplotlib, Keras-Preprocessing, jax, imbalanced-learn, imageio, imagecodecs, h5py, datasets, daal4py, Bottleneck, bokeh, bkcharts, astropy
Note: you may need to restart the kernel to use updated packages.


#### List

In [1]:
fruits = ['apple', 'mango', 'banana']
print(fruits)

['apple', 'mango', 'banana']


### 2. Arrays

In [3]:
# Array
import numpy as np
arr = np.array(fruits)
print(arr)
print(type(fruits))
print(type(arr))

['apple' 'mango' 'banana']
<class 'list'>
<class 'numpy.ndarray'>


### 2. Difference between Array and List

In [29]:
fruits = [2, 'apple', 3.0]
print(fruits)

[2, 'apple', 3.0]


In [30]:
arr2 = np.array([2, 'apple', 3.0])
print(arr2)
print(arr2.dtype)

['2' 'apple' '3.0']
<U32


###### Array cannot store mixed type data

### 3. Default data types of array

In [31]:
arr3 = np.array([2, 4, 6])
print(arr3)
print(arr3.dtype)

[2 4 6]
int32


In [32]:
arr3 = np.array([2.0, 4.0, 6.0])
print(arr3)
print(arr3.dtype)

[2. 4. 6.]
float64


### 3. Dimension of Arrays

* #### 0-D Arrays
* #### 1-D Arrays
* #### 2-D Arrays
* #### 3-D Arrays
* #### N-D Arrays

In [4]:
arr1 = np.array(34)
print(arr1)
print('Dimension:', arr1.ndim)

34
Dimension: 0


#### 1-D Arrays

In [5]:
arr2 = np.array([10, 20, 30, 40])
print(arr2)
print('Dimension:', arr2.ndim)

[10 20 30 40]
Dimension: 1


#### 2-D Arrays

In [6]:
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr3)
print('Dimension:', arr3.ndim)

[[1 2 3]
 [4 5 6]]
Dimension: 2


#### 3-D Arrays

In [7]:
arr4 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr4)
print('Dimension:', arr4.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Dimension: 3


### 4. Specifying data types of Array

In [40]:
arr3 = np.array([2.9, 4.0, 6.0], dtype = 'int8')
print(arr3)
print(arr3.dtype)

[2 4 6]
int8


In [41]:
arr3 = np.array([152, 10, 90], dtype = 'int8')
print(arr3)
print(arr3.dtype)

[-104   10   90]
int8


In [42]:
arr3 = np.array([152, 10, 90], dtype = 'int16')
print(arr3)
print(arr3.dtype)

[152  10  90]
int16


### 4. Array Attributes

In [11]:
# Shape of array
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr3)
print('Shape:', arr3.shape)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [12]:
# size of array
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr3)
print('Size:', arr3.size)

[[1 2 3]
 [4 5 6]]
Size: 6


In [13]:
# itemsize
arr3 = np.array([152, 10, 90], dtype = 'int16')
print(arr3)
print('Itemsize:', arr3.itemsize)

[152  10  90]
Itemsize: 2


### 5. Accessing elements

In [54]:
arr3 = np.array(['apple', 'banana', 'cherry', 'mango', 'orange'])
print(arr3[2])
print(arr3[-2])
print(arr3[1:4])

cherry
mango
['banana' 'cherry' 'mango']


In [66]:
# accessing elements of 2D array
arr3 = np.array([[10, 20, 30], [40, 50, 60]])
print(arr3)
print('--------------------')
print(arr3[0:2, 1:])

[[10 20 30]
 [40 50 60]]
--------------------
[[20 30]
 [50 60]]


### 6. Creation Routines

* #### Empty

In [2]:
arr = np.empty([3,3], dtype = 'int')
print(arr)

[[-537329408        545    5570638]
 [   6225997    4718676    4522066]
 [   4456513         83          0]]


In [4]:
arr2 = np.empty([3,3], dtype = 'float')
print(arr2)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 7.11454530e-321]
 [5.08566454e-028 4.11366171e+223 1.02303531e+200]]


* #### Zeros

In [7]:
arr = np.zeros([3, 3] )
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


* #### Ones

In [10]:
# numpy.ones(shape,dtype)
x = np.ones([2,2])
print(x)

[[1. 1.]
 [1. 1.]]


* #### Eye

In [15]:
# eye
arr  = np.eye(4, k = 2)
print(arr)

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
arr = np.identity(4, dtype='int')
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [24]:
# arange
arr = np.arange(10, 105, 5)
print(arr)

[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100]


In [27]:
li = range(10, 105, 5)
arr  = np.array(li)
print(arr)

[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100]


In [35]:
x = np.array([1,2])
print(x)
x = np.asmatrix(x)
print(x)


[1 2]
[[1 2]]


### Arthimetic Operation

In [40]:
# addition
arr1 = np.array([2,4,6,8])
arr2 = np.array([1,5,6,2])
print(arr1 + arr2)
print('-----------------')
print(np.add(arr1, arr2))

[ 3  9 12 10]
-----------------
[ 3  9 12 10]


In [41]:
# subtraction
arr1 = np.array([2,4,6,8])
arr2 = np.array([1,5,6,2])
print(arr1 - arr2)
print('-----------------')
print(np.subtract(arr1, arr2))

[ 1 -1  0  6]
-----------------
[ 1 -1  0  6]


In [42]:
# multiplication
arr1 = np.array([2,4,6,8])
arr2 = np.array([1,5,6,2])
print(arr1 * arr2)
print('-----------------')
print(np.multiply(arr1, arr2))

[ 2 20 36 16]
-----------------
[ 2 20 36 16]


In [52]:
arr1 = np.array([2,4,6,8])
print(arr1.shape)
print(arr1)
print('-----------------')
arr2 = np.array([[1,5,6,2], [1,3,5,7], [1,4,6,8], [1,3,4,4]])
print(arr2)
print(arr2.shape)
print(np.matmul(arr1, arr2))

(4,)
[2 4 6 8]
-----------------
[[1 5 6 2]
 [1 3 5 7]
 [1 4 6 8]
 [1 3 4 4]]
(4, 4)
[ 20  70 100 112]


In [54]:
# Division
arr1 = np.array([2,4,6,8])
arr2 = np.array([1,5,6,2])
print(arr1 / arr2)
print('-----------------')
print(np.divide(arr1, arr2))

[2.  0.8 1.  4. ]
-----------------
[2.  0.8 1.  4. ]


In [57]:
# mod
arr1 = np.array([2,4,6,8])
arr2 = np.array([1,5,6,2])
print(arr1 % arr2)
print('-----------------')
print(np.mod(arr1, arr2))
print(np.remainder(arr1, arr2))

[0 4 0 0]
-----------------
[0 4 0 0]
[0 4 0 0]


In [58]:
# greater
arr1 = np.array([2,4,6,8])
arr2 = np.array([1,5,6,2])
print(arr1 > arr2)
print('-----------------')
print(np.greater(arr1, arr2))

[ True False False  True]
-----------------
[ True False False  True]


In [59]:
# greater
arr1 = np.array([2,4,6,8])
arr2 = np.array([1,5,6,2])
print(arr1 < arr2)
print('-----------------')
print(np.less(arr1, arr2))

[False  True False False]
-----------------
[False  True False False]


In [60]:
arr2D = np.array([[8, 7, 1, 2], [3, 2, 3, 1],
[29, 32, 11, 9]])
print(arr2D)
print('----------------')
arr2D.sort(axis=0)
print('Sorted Array : ')
print(arr2D)

[[ 8  7  1  2]
 [ 3  2  3  1]
 [29 32 11  9]]
----------------
Sorted Array : 
[[ 3  2  1  1]
 [ 8  7  3  2]
 [29 32 11  9]]


In [67]:
arr2D = np.array([[8, 7, 1, 2], [3, 2, 3, 1],
[29, 32, 11, 9]])
print(arr2D)
print('----------------')
arr2D.sort(axis=0)
print('Sorted Array : ')
print(arr2D)

[[ 8  7  1  2]
 [ 3  2  3  1]
 [29 32 11  9]]
----------------
Sorted Array : 
[[ 3  2  1  1]
 [ 8  7  3  2]
 [29 32 11  9]]
